# Generated by Django 5.0.7 on 2025-12-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mpikambana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anarana', models.CharField(max_length=50, null=True)),
                ('Fanampiny', models.CharField(max_length=50, null=True)),
                ('Totem', models.CharField(max_length=50, null=True)),
                ('Andraikitra', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sampana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anarana', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
